module Euler002 where

-- | Problem 2
--
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
--
--   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- Find the sum of all the even-valued terms in the sequence which do not
-- exceed four million.
--
-- >>> euler002
-- 4613732

fib :: [Integer]
fib = 1 : 2 : fib' 1 2
  where fib' x y = x + y : fib' y (x + y)

euler002 :: Integer
euler002 = sum $ takeWhile (<4000000) $ filter even $ fib
