module Euler002 where

-- | Problem 2
--
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
--
--   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- Find the sum of all the even-valued terms in the sequence which do not
-- exceed four million.
--
-- >>> euler002 4000000
-- 4613732

fib :: [Integer]
fib = fib' 0 1
  where fib' x y = let z = x + y in z : fib' y z

euler002 :: Integer -> Integer
euler002 n = sum $ takeWhile (< n) $ filter even $ fib
